version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=property_management.settings
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  db:
    image: postgres:14.5
    environment:
      POSTGRES_DB: property_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bittecnologies123
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: