# Generated by Django 5.0.6 on 2024-07-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='surface',
            field=models.CharField(max_length=10),
        ),
    ]
