version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: property_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Juanpablo7823
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
    command: /app/start.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=property_db
      - DB_USER=postgres
      - DB_PASSWORD=Juanpablo7823

volumes:
  postgres_data: